server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/paredesdaniel1721/config-data
          search-paths: / #config-data
  security:
    user:
      name: root
      password: s3cr3t
