server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/paredesdaniel1721/config-data.git
          searchPaths: / #config-data
  security:
    user:
      name: root
      password: s3cr3t